version: '3.3'
services:
  jupyter:
    build:
      context: .
      dockerfile: deploy/jupyter.Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
    secrets:
      - postgres_password
    command: "-m jupyter notebook . --ip=0.0.0.0 --port=3000 --allow-root --NotebookApp.token='' --NotebookApp.password=''"
secrets:
  postgres_password:
    file: private/postgres_password